services:
  serverless:
    platform: "linux/amd64"
    image: amaysim/serverless:3.36.0
    command: serverless
    working_dir: /opt/app/
    volumes:
    - .:/opt/app
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_SESSION_TOKEN:
      AWS_SECURITY_TOKEN:

  compile:
    platform: "linux/amd64"
    build:
      context: .
    volumes:
    - .:/var/task/
    command: /var/task/.buildkite/bundle.sh
